"""
config.py — single source of truth for all data paths.

Set nothing here unless a folder actually moves. Every notebook does:
    from config import *
and then uses JIN_REPO, NEURAL_PATH, SURVEY_DIR, etc. — no more per-notebook path edits.

All paths are derived from REPO (this file's folder), so they work as long as config.py
sits at the repo root and you run the notebooks from the repo root. Verified present on disk
except the two intermediates noted at the bottom (you generate those in Step 6).
"""
import os
from pathlib import Path

REPO = os.path.dirname(os.path.abspath(__file__))
def _d(*p):  # helper: join under data/
    return os.path.join(REPO, "data", *p)

# ── Jin's cloned repo (lives under data/socialaha) ─────────────────────────────
JIN_REPO        = _d("socialaha")
NEURAL_PATH     = os.path.join(JIN_REPO, "data/brain/similarity/neuralISC_byevent.npy")
IMPR_PATH       = os.path.join(JIN_REPO, "data/beh/similarity/impressions_byrun_bychar.npy")
EVENT_PATH      = os.path.join(JIN_REPO, "data/beh/annotations/socialaha_groupscene.csv")  # group-scene char-per-run
BIDS_EVENTS_DIR = os.path.join(JIN_REPO, "data/brain/events")                              # onset/duration (step06)

# ── original shared collab folder (surveys, atlas, masks, aha annotations) ─────
OG              = _d("ALL DATA OG SHARE socialaha-collab")
SURVEY_DIR      = Path(os.path.join(OG, "socialaha-fMRI", "charactersurvey"))   # post-scan 35-item survey (.mat)
TEMPLATE_DIR    = os.path.join(OG, "template")                                  # Schaefer-100 + Tian-16 atlas
AHA_ANNOT_PATH  = os.path.join(OG, "socialaha-fMRI", "ahaannot_rhea_allcateg.xlsx")  # swap annotator if needed

# ── behavioral SONA 16-item survey + the transcript Step 0 scores ──────────────
BEH_DIR         = Path(_d("charsurvey"))
TRANSCRIPT_PATH = _d("clean_from_jin", "socialaha_transcribe_rhea_char_updated_clean_jin.csv")

# ── Step-0 character-onset events (event_type schema — different from BIDS events) ──
# 00 maps the transcript's `order` column to a character name via these. External to the repo.
EVENTS_TSV_ORDER = "/Users/rheamadhogarhia/Desktop/CABLAB RESEARCH/independent ra work/part_4_summer_char_profiles/events.tsvs"

# ── Step-6 neural pattern-shift ────────────────────────────────────────────────
LOADED_BOLD_DIR    = _d()   # your ROIsum_combined_mask_g{1,2,3}.pkl live directly in data/
PATTERN_SHIFT_PATH = os.path.join(JIN_REPO, "data/brain/pattern_shift/1TR_nearbytp.npy")  # generated by 06 (6.0c)

# ── results (created by the pipeline; relative to repo root) ───────────────────
RESULTS = os.path.join(REPO, "results")
